/*
 * Uber API
 *
 * Move your app forward with the Uber API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	routers "assignment2/swagger"

)

func main() {
	routers.InitDb()
	log.Printf("Server started")

	router := routers.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
